import type { Company } from "./types";

export const COMPANIES: Company[] = [
  {
    id: "NMSH",
    name: "NeuralMesh AI",
    sector: "AI / Enterprise SaaS",
    stage: "Seed",
    platform: "Wefunder",
    status: "Live",
    raised: 847000,
    target: 1200000,
    valuationCap: 12000000,
    pricePerShare: 1.20,
    securityType: "SAFE",
    investors: 312,
    cashOnHand: 320000,
    monthlyBurn: 45000,
    revenue: 18000,
    revenueGrowthPct: 34,
    grossMarginPct: 72,
    totalDebt: 190000,
    employees: 8,
    location: "Austin, TX",
    ceo: "Priya Nair",
    cto: "Marcus Chen",
    description: "AI-powered workflow automation for mid-market enterprises. Reduces manual data entry by 80% using domain-specific LLMs trained on customer data.",
    filingDate: "2025-11-14",
    formType: "C",
    cik: "0001987654",
    quarterlyRevenue: [22000, 30000, 40000, 54000],
    quarterlyBurn:    [120000, 130000, 138000, 135000],
    quarterlyCash:    [600000, 490000, 390000, 320000],
    quarterLabels:    ["Q1 2025", "Q2 2025", "Q3 2025", "Q4 2025"],
    xbrl: {
      totalAssets:        350000,
      currentAssets:      335000,
      cash:               320000,
      accountsReceivable: 15000,
      totalLiabilities:   200000,
      currentLiabilities: 195000,
      stockholdersEquity: 150000,
      revenue:            146000,
      cogs:               40880,
      operatingExpenses:  540000,
      netIncome:          -434880,
    },
    riskFactors: [
      "68% of revenue concentrated in 3 clients — loss of any single customer could materially impair operations and delay path to profitability.",
      "OpenAI API dependency creates platform risk — price increases or API deprecation could compress margins or require costly re-architecture.",
      "7-month cash runway without additional funding; if current raise does not close, the company may be unable to fund operations through Q3 2026.",
    ],
    useOfProceeds: {
      "Product Dev": 40,
      "Sales & Mktg": 30,
      "Operations": 20,
      "Legal & Compliance": 10,
    },
    aiAnalysis: {
      verdict: "Cautious Optimism",
      conviction: "MODERATE",
      riskLevel: 3,
      plainEnglish: "Think of NeuralMesh like a popular restaurant with a growing customer base — but they only have 7 months of rent in the bank. The food is getting better and more people are showing up, but the clock is ticking.",
      summary: "NeuralMesh shows genuine product-market fit with 34% QoQ revenue growth and 72% gross margins, but the compressed runway creates urgency. Success depends on closing this raise quickly and converting pipeline to recurring contracts.",
      bullCase: "Revenue has 4x'd in 12 months, 14 enterprise customers with 94% retention, and the AI workflow automation market is growing at 38% CAGR. If they hit $50K MRR by Q2 2026, runway extends dramatically.",
      bearCase: "Client concentration (68% from 3 accounts), OpenAI dependency, and a 7-month runway create compounding risk. A single churn event could trigger a downward spiral before the next raise.",
    },
    market: {
      askPrice: 1.35,
      bidPrice: 1.08,
      volume24h: 24200,
      trades24h: 18,
    },
  },
  {
    id: "CBOT",
    name: "CompliBot",
    sector: "RegTech / Compliance AI",
    stage: "Seed+",
    platform: "Republic",
    status: "Live",
    raised: 2100000,
    target: 3000000,
    valuationCap: 28000000,
    pricePerShare: 2.80,
    securityType: "Preferred Equity",
    investors: 891,
    cashOnHand: 1850000,
    monthlyBurn: 120000,
    revenue: 95000,
    revenueGrowthPct: 67,
    grossMarginPct: 85,
    totalDebt: 350000,
    employees: 24,
    location: "New York, NY",
    ceo: "Daniel Osei",
    cto: "Sonia Patel",
    description: "AI-powered compliance monitoring platform for community banks and credit unions. Automatically detects regulatory violations in real-time, replacing $2,400/month manual compliance consultants.",
    filingDate: "2025-10-02",
    formType: "C",
    cik: "0001876543",
    quarterlyRevenue: [61000, 102000, 171000, 285000],
    quarterlyBurn:    [300000, 330000, 360000, 360000],
    quarterlyCash:    [2800000, 2500000, 2200000, 1850000],
    quarterLabels:    ["Q1 2025", "Q2 2025", "Q3 2025", "Q4 2025"],
    xbrl: {
      totalAssets:        2300000,
      currentAssets:      2100000,
      cash:               1850000,
      accountsReceivable: 250000,
      totalLiabilities:   900000,
      currentLiabilities: 840000,
      stockholdersEquity: 1400000,
      revenue:            619000,
      cogs:               92850,
      operatingExpenses:  1440000,
      netIncome:          -913850,
    },
    riskFactors: [
      "28x revenue valuation implies aggressive growth expectations — multiple compression risk if growth slows below 50% QoQ.",
      "Thomson Reuters, MSCI, and Bloomberg Legal all have compliance automation products and could bundle offerings to undercut pricing.",
      "Regulatory deregulation under shifting political environments could reduce compliance burden, shrinking the addressable market.",
    ],
    useOfProceeds: {
      "Engineering": 35,
      "Sales & Mktg": 30,
      "Compliance Infra": 25,
      "Admin & Legal": 10,
    },
    aiAnalysis: {
      verdict: "Favorable",
      conviction: "HIGH",
      riskLevel: 2,
      plainEnglish: "CompliBot is like a 24/7 security alarm system for banks that watches for regulatory violations. Banks legally must have compliance monitoring — they don't choose to buy it, they're required to. That makes customers very sticky.",
      summary: "CompliBot has the strongest fundamentals in this cohort: 85% gross margins, 67% QoQ growth, 15+ months runway, and a regulatory-mandated use case. The $28M valuation is aggressive but defensible if current growth rates hold through 2026.",
      bullCase: "85% gross margins with 48 sticky institutional customers suggests genuine product-market fit. Regulatory tailwind from increasing compliance requirements creates durable demand. Path to $1M ARR is visible within 3 quarters.",
      bearCase: "Trading at 24x revenue requires sustained hyper-growth. Enterprise sales cycles are long (90-120 days), and any large incumbent entering the space could instantly freeze the sales pipeline.",
    },
    market: {
      askPrice: 2.95,
      bidPrice: 2.65,
      volume24h: 85400,
      trades24h: 34,
    },
  },
  {
    id: "HLNS",
    name: "HealthLens",
    sector: "Digital Health / MedTech",
    stage: "Pre-Seed",
    platform: "StartEngine",
    status: "Live",
    raised: 430000,
    target: 800000,
    valuationCap: 6000000,
    pricePerShare: 0.60,
    securityType: "SAFE",
    investors: 624,
    cashOnHand: 95000,
    monthlyBurn: 62000,
    revenue: 3200,
    revenueGrowthPct: 12,
    grossMarginPct: 45,
    totalDebt: 165000,
    employees: 5,
    location: "Denver, CO",
    ceo: "Dr. Amara Okonkwo",
    cto: "James Whitfield",
    description: "AI-powered diagnostic imaging tool for rural clinics lacking specialist access. FDA 510(k) clearance pending. Enables early detection of 6 conditions from standard X-rays using on-device ML models.",
    filingDate: "2025-09-18",
    formType: "C",
    cik: "0001765432",
    quarterlyRevenue: [6800, 7700, 8600, 9600],
    quarterlyBurn:    [160000, 175000, 185000, 186000],
    quarterlyCash:    [600000, 440000, 260000, 95000],
    quarterLabels:    ["Q1 2025", "Q2 2025", "Q3 2025", "Q4 2025"],
    xbrl: {
      totalAssets:        100000,
      currentAssets:      100000,
      cash:               95000,
      accountsReceivable: 5000,
      totalLiabilities:   165000,
      currentLiabilities: 160000,
      stockholdersEquity: -65000,
      revenue:            32700,
      cogs:               17985,
      operatingExpenses:  744000,
      netIncome:          -729285,
    },
    riskFactors: [
      "FDA 510(k) clearance is binary — rejection or delay eliminates primary revenue path and likely forces company wind-down.",
      "Negative stockholders equity (-$65K) indicates technical insolvency; current liabilities exceed total assets by $65,000.",
      "5% revenue-to-burn coverage means operations are unsustainable without immediate capital injection — 6-week runway as of last filing.",
    ],
    useOfProceeds: {
      "FDA Process": 50,
      "Product Dev": 30,
      "Team": 15,
      "Legal": 5,
    },
    aiAnalysis: {
      verdict: "High Risk",
      conviction: "LOW",
      riskLevel: 5,
      plainEnglish: "A brilliant doctor invented an amazing diagnostic tool for rural hospitals — but she's almost out of money and the FDA hasn't approved it yet. Noble mission, critical financial situation.",
      summary: "HealthLens addresses a genuine healthcare gap, but the financial profile is critically distressed. With 6 weeks of cash, negative equity, and binary FDA dependency, this investment requires conviction that the FDA will clear the device imminently.",
      bullCase: "FDA clearance unlocks a $4.2B rural diagnostics market with no direct AI competitor. 50+ rural clinic LOIs represent immediate post-clearance revenue. If funded and cleared, revenue could scale 100x within 18 months.",
      bearCase: "Technical insolvency, 6-week runway, and FDA binary risk create a trifecta of existential threats. Revenue covers only 5% of burn. Without this raise AND FDA clearance, the company cannot survive past Q1 2026.",
    },
    market: {
      askPrice: 0.65,
      bidPrice: 0.45,
      volume24h: 8100,
      trades24h: 6,
    },
  },
  {
    id: "SYNK",
    name: "SynkPay",
    sector: "Fintech / Payments",
    stage: "Seed",
    platform: "Republic",
    status: "Closed",
    raised: 5000000,
    target: 5000000,
    valuationCap: 42000000,
    pricePerShare: 4.20,
    securityType: "Preferred Equity",
    investors: 1847,
    cashOnHand: 4200000,
    monthlyBurn: 180000,
    revenue: 210000,
    revenueGrowthPct: 89,
    grossMarginPct: 62,
    totalDebt: 900000,
    employees: 41,
    location: "Miami, FL",
    ceo: "Carlos Mendez",
    cto: "Aisha Kone",
    description: "Real-time payment infrastructure for Latin America. Enables instant, low-cost cross-border transfers for individuals and SMBs across 14 LATAM countries using local payment rails + stablecoin settlement.",
    filingDate: "2025-08-22",
    formType: "C",
    cik: "0001654321",
    quarterlyRevenue: [93000, 176000, 333000, 630000],
    quarterlyBurn:    [480000, 510000, 540000, 540000],
    quarterlyCash:    [5200000, 4900000, 4600000, 4200000],
    quarterLabels:    ["Q1 2025", "Q2 2025", "Q3 2025", "Q4 2025"],
    xbrl: {
      totalAssets:        5200000,
      currentAssets:      4900000,
      cash:               4200000,
      accountsReceivable: 700000,
      totalLiabilities:   1600000,
      currentLiabilities: 1500000,
      stockholdersEquity: 3600000,
      revenue:            1232000,
      cogs:               468160,
      operatingExpenses:  2160000,
      netIncome:          -1396160,
    },
    riskFactors: [
      "$42M valuation at current revenue requires 100x+ returns to generate VC-scale outcomes, creating significant multiple expansion pressure.",
      "FX volatility across 14 LATAM currencies creates margin compression risk — a 10% currency swing in BRL or MXN directly impacts unit economics.",
      "Venmo International, PayPal LATAM, and Wise all have 10x+ the capital and engineering resources and are actively expanding in target markets.",
    ],
    useOfProceeds: {
      "Tech Infra": 40,
      "LATAM Expansion": 35,
      "Compliance": 15,
      "Team": 10,
    },
    aiAnalysis: {
      verdict: "Strong",
      conviction: "HIGH",
      riskLevel: 2,
      plainEnglish: "SynkPay is like FedEx for money in Latin America — fast, cheap, and reliable cross-border payments. They've already proven people want it, they're near break-even, and they have 23 months of runway to keep growing.",
      summary: "SynkPay shows what institutional-grade execution looks like at the Seed stage: 89% QoQ growth, $210K MRR approaching burn breakeven, 23+ months runway, and 267 paying customers. The $42M valuation is ambitious but growth supports it.",
      bullCase: "89% QoQ revenue growth with 267 paying SMB customers demonstrates product-market fit. LATAM cross-border payments is a $180B market growing at 22% CAGR. Near-breakeven economics at $210K MRR suggests capital efficiency.",
      bearCase: "$42M valuation at 16x annualized revenue leaves little margin for growth slowdown. Currency risk across LATAM is structural and difficult to fully hedge. Large incumbents can acquire market share through aggressive pricing.",
    },
    market: {
      askPrice: 4.50,
      bidPrice: 4.10,
      volume24h: 152000,
      trades24h: 52,
    },
  },
];

export const companies = COMPANIES;

export function getCompany(id: string): Company | undefined {
  return COMPANIES.find((c) => c.id === id);
}
